import { PaymentChannel, PayoutTransaction } from "@/types/payout";

export const COIN_RATE = 35; // 1 Poin = Rp 35
export const MIN_WITHDRAW_POINTS = 100; // Minimal 100 poin = Rp 3.500

export const PAYMENT_CHANNELS: PaymentChannel[] = [
  // Banks
  {
    id: "bca",
    name: "Bank Central Asia (BCA)",
    type: "bank",
    icon: "account_balance",
    code: "BCA",
    accountPlaceholder: "Contoh: 1234567890",
  },
  {
    id: "mandiri",
    name: "Bank Mandiri",
    type: "bank",
    icon: "account_balance",
    code: "MANDIRI",
    accountPlaceholder: "Contoh: 1400012345678",
  },
  {
    id: "bri",
    name: "Bank Rakyat Indonesia (BRI)",
    type: "bank",
    icon: "account_balance",
    code: "BRI",
    accountPlaceholder: "Contoh: 012301001234567",
  },
  {
    id: "bni",
    name: "Bank Negara Indonesia (BNI)",
    type: "bank",
    icon: "account_balance",
    code: "BNI",
    accountPlaceholder: "Contoh: 0123456789",
  },
  // E-Wallets
  {
    id: "gopay",
    name: "GoPay",
    type: "ewallet",
    icon: "account_balance_wallet",
    code: "GOPAY",
    accountPlaceholder: "Nomor HP GoPay (08xxxxxxxxxx)",
  },
  {
    id: "ovo",
    name: "OVO",
    type: "ewallet",
    icon: "account_balance_wallet",
    code: "OVO",
    accountPlaceholder: "Nomor HP OVO (08xxxxxxxxxx)",
  },
  {
    id: "dana",
    name: "DANA",
    type: "ewallet",
    icon: "account_balance_wallet",
    code: "DANA",
    accountPlaceholder: "Nomor HP DANA (08xxxxxxxxxx)",
  },
  {
    id: "shopeepay",
    name: "ShopeePay",
    type: "ewallet",
    icon: "account_balance_wallet",
    code: "SHOPEEPAY",
    accountPlaceholder: "Nomor HP ShopeePay (08xxxxxxxxxx)",
  },
];

export const INITIAL_PAYOUT_HISTORY: PayoutTransaction[] = [
  {
    id: "WD-849201",
    date: "Hari ini",
    time: "10:30 WIB",
    fullDate: "25 Agustus 2026, 10:30 WIB",
    channelName: "Bank Central Asia (BCA)",
    channelType: "bank",
    accountNumber: "8730192841",
    accountHolderName: "Budi Santoso",
    pointsDeducted: 600,
    amountIdr: 30000,
    adminFeeIdr: 0,
    netAmountIdr: 30000,
    status: "processing",
    estimatedArrival: "Hari ini, dalam 5-15 menit (Maks. 1x24 jam)",
  },
  {
    id: "WD-819034",
    date: "20 Agu 2026",
    time: "14:15 WIB",
    fullDate: "20 Agustus 2026, 14:15 WIB",
    channelName: "GoPay",
    channelType: "ewallet",
    accountNumber: "081298765432",
    accountHolderName: "Budi Santoso",
    pointsDeducted: 500,
    amountIdr: 25000,
    adminFeeIdr: 0,
    netAmountIdr: 25000,
    status: "completed",
    estimatedArrival: "Selesai",
    completedAt: "20 Agu 2026, 14:18 WIB",
  },
  {
    id: "WD-791022",
    date: "12 Agu 2026",
    time: "09:00 WIB",
    fullDate: "12 Agustus 2026, 09:00 WIB",
    channelName: "Bank Mandiri",
    channelType: "bank",
    accountNumber: "1400019283741",
    accountHolderName: "Budi Santoso",
    pointsDeducted: 1000,
    amountIdr: 50000,
    adminFeeIdr: 0,
    netAmountIdr: 50000,
    status: "completed",
    estimatedArrival: "Selesai",
    completedAt: "12 Agu 2026, 09:05 WIB",
  },
];
