import { TransactionDetail, WasteCategoryKey } from "@/types/transaction";

export interface CategoryOption {
  key: WasteCategoryKey;
  label: string;
  icon: string;
  color: string;
  bgColor: string;
  borderColor: string;
}

export const CATEGORY_OPTIONS: CategoryOption[] = [
  {
    key: "all",
    label: "Semua Kategori",
    icon: "category",
    color: "#006c49",
    bgColor: "#eff4ff",
    borderColor: "#bbcabf",
  },
  {
    key: "cup_plastik",
    label: "Cup Plastik",
    icon: "coffee",
    color: "#0284c7",
    bgColor: "#f0f9ff",
    borderColor: "#bae6fd",
  },
  {
    key: "botol_plastik",
    label: "Botol Plastik",
    icon: "local_drink",
    color: "#15803d",
    bgColor: "#f0fdf4",
    borderColor: "#bbf7d0",
  },
  {
    key: "tutup_cup",
    label: "Tutup Cup",
    icon: "takeout_dining",
    color: "#7c3aed",
    bgColor: "#faf8ff",
    borderColor: "#ddd6fe",
  },
  {
    key: "kardus",
    label: "Kardus & Box",
    icon: "package_2",
    color: "#d97706",
    bgColor: "#fffbeb",
    borderColor: "#fde68a",
  },
  {
    key: "kaleng",
    label: "Kaleng Minuman",
    icon: "inventory_2",
    color: "#0f766e",
    bgColor: "#f0fdfa",
    borderColor: "#99f6e4",
  },
  {
    key: "ampas_kopi",
    label: "Ampas Kopi",
    icon: "compost",
    color: "#854d0e",
    bgColor: "#fefce8",
    borderColor: "#fef08a",
  },
];

export const INITIAL_TRANSACTIONS: TransactionDetail[] = [
  {
    id: "RB-984210",
    categoryKey: "cup_plastik",
    material: "Cup Plastik PP Bekas Kopi",
    date: "Hari ini",
    time: "09:15 WIB",
    fullDate: "25 Agustus 2026, 09:15 WIB",
    weightKg: 3.2,
    pointsEarned: 16,
    co2SavedKg: 3.8,
    status: "confirmed",
    method: "drop_point",
    dropPointName: "ReBrew Micro-Hub Surabaya Timur",
    verifiedAt: "25 Agu 2026, 09:20 WIB",
    scaleModel: "IoT Smart Scale v2.4",
    notes: "Cup dicuci bersih dan ditumpuk rapi.",
  },
  {
    id: "RB-983192",
    categoryKey: "tutup_cup",
    material: "Tutup Cup Plastik & Sedotan",
    date: "Hari ini",
    time: "09:15 WIB",
    fullDate: "25 Agustus 2026, 09:15 WIB",
    weightKg: 1.5,
    pointsEarned: 5,
    co2SavedKg: 1.2,
    status: "confirmed",
    method: "drop_point",
    dropPointName: "ReBrew Micro-Hub Surabaya Timur",
    verifiedAt: "25 Agu 2026, 09:20 WIB",
    scaleModel: "IoT Smart Scale v2.4",
    notes: "Lid PET & PP bening.",
  },
  {
    id: "RB-978104",
    categoryKey: "botol_plastik",
    material: "Botol Plastik PET Mineral & Sirup",
    date: "Kemarin",
    time: "14:30 WIB",
    fullDate: "24 Agustus 2026, 14:30 WIB",
    weightKg: 4.8,
    pointsEarned: 48,
    co2SavedKg: 6.7,
    status: "confirmed",
    method: "drop_point",
    dropPointName: "ReBrew Point - Kopi Selamat Cafe",
    verifiedAt: "24 Agu 2026, 14:40 WIB",
    scaleModel: "ReBrew Calibrated Scale #02",
    notes: "Botol dipipihkan dan tanpa tutup.",
  },
  {
    id: "RB-972418",
    categoryKey: "kardus",
    material: "Kardus Kemasan Susu & Sirup",
    date: "23 Agu 2026",
    time: "11:00 WIB",
    fullDate: "23 Agustus 2026, 11:00 WIB",
    weightKg: 6.5,
    pointsEarned: 83, // Diskon 15% pickup
    co2SavedKg: 5.9,
    status: "confirmed",
    method: "dijemput",
    pickupAddress: "Kopi Selamat Cafe, Jl. Raya Gubeng No. 18, Surabaya",
    collectorName: "ReBrew Driver #04 (Deni)",
    verifiedAt: "23 Agu 2026, 11:15 WIB",
    notes: "Kardus kering dan dilipat rapi dalam ikatan.",
  },
  {
    id: "RB-968921",
    categoryKey: "kaleng",
    material: "Kaleng Susu Evaporasi & Krimer",
    date: "21 Agu 2026",
    time: "16:20 WIB",
    fullDate: "21 Agustus 2026, 16:20 WIB",
    weightKg: 2.1,
    pointsEarned: 42,
    co2SavedKg: 5.3,
    status: "confirmed",
    method: "drop_point",
    dropPointName: "Bank Sampah Induk Surabaya",
    verifiedAt: "21 Agu 2026, 16:35 WIB",
    scaleModel: "Digital Precision Scale 50kg",
    notes: "Kaleng dibilas bersih.",
  },
  {
    id: "RB-965412",
    categoryKey: "ampas_kopi",
    material: "Ampas Espresso & Manual Brew",
    date: "19 Agu 2026",
    time: "10:10 WIB",
    fullDate: "19 Agustus 2026, 10:10 WIB",
    weightKg: 5.0,
    pointsEarned: 25,
    co2SavedKg: 3.0,
    status: "confirmed",
    method: "drop_point",
    dropPointName: "ReBrew Micro-Hub Surabaya Timur",
    verifiedAt: "19 Agu 2026, 10:25 WIB",
    notes: "Ampas kopi dikeringkan untuk briket arang.",
  },
  {
    id: "RB-959102",
    categoryKey: "cup_plastik",
    material: "Cup Plastik Boba & Es Kopi",
    date: "18 Agu 2026",
    time: "13:45 WIB",
    fullDate: "18 Agustus 2026, 13:45 WIB",
    weightKg: 2.0,
    pointsEarned: 10,
    co2SavedKg: 2.4,
    status: "pending",
    method: "drop_point",
    dropPointName: "ReBrew Point - Kopi Selamat Cafe",
    notes: "Menunggu penimbangan fisik oleh petugas drop point.",
  },
  {
    id: "RB-954318",
    categoryKey: "botol_plastik",
    material: "Botol Plastik Oli / Kimiawi",
    date: "15 Agu 2026",
    time: "08:30 WIB",
    fullDate: "15 Agustus 2026, 08:30 WIB",
    weightKg: 1.0,
    pointsEarned: 0,
    co2SavedKg: 0,
    status: "rejected",
    method: "drop_point",
    dropPointName: "ReBrew Micro-Hub Surabaya Timur",
    notes: "Ditolak: Mengandung residu B3 berbahaya yang tidak dapat didaur ulang.",
  },
];
