import { DashboardData } from "@/types/dashboard";

export const initialDashboardData: DashboardData = {
  user: {
    id: "usr-01",
    name: "Budi Santoso",
    email: "mitra@kopiselamat.com",
    cafeName: "Kopi Selamat Cafe",
    tier: "starter",
    tierLabel: "Eco Partner ⭐",
    city: "Surabaya",
    rankInCity: 2,
    totalCafesInCity: 48,
  },
  stats: {
    totalCoins: 1480,
    balanceIdr: 74000,
    wasteKgThisMonth: 14.6,
    targetKgThisMonth: 25.0,
    co2SavedKg: 7.3,
    plasticCupsRecycled: 420,
    activeStreakDays: 6,
  },
  target: {
    currentKg: 14.6,
    targetKg: 25.0,
    monthName: "Agustus 2026",
    rewardBonusCoins: 150,
    rewardBadgeName: "1 Ton Club Contender",
  },
  deviceStatus: {
    scaleStatus: "online",
    scaleModel: "ReBrew IoT Scale v2.4 (Bluetooth BLE & WiFi)",
    scaleLastSync: "2 menit lalu",
    nextPickupDate: "Belum Ada Jadwal",
    nextPickupTime: "",
    collectorName: "ReBrew Micro-Hub Surabaya",
    collectorPhone: "0812-3456-7890",
  },
  notification: {
    id: "RB-A1B2C3",
    message: "Setoran RB-A1B2C3 Terverifikasi!",
    detail:
      "Timbangan IoT mencatat 2.4 kg Cup Plastik & 1.2 kg Tutup Cup · +16 Koin ditambahkan",
    coinsEarned: 16,
    timestamp: "10 menit lalu",
  },
  recentTransactions: [
    {
      id: "RB-781",
      categoryKey: "cup_plastik",
      material: "Cup Plastik PP",
      date: "Hari ini 09:15",
      weightKg: 2.4,
      coins: 12,
      status: "confirmed",
      method: "drop_point",
      dropPointName: "ReBrew Hub Gubeng",
    },
    {
      id: "RB-780",
      categoryKey: "tutup_cup",
      material: "Tutup Cup & Seal",
      date: "Hari ini 09:15",
      weightKg: 1.2,
      coins: 4,
      status: "confirmed",
      method: "drop_point",
      dropPointName: "ReBrew Hub Gubeng",
    },
    {
      id: "RB-779",
      categoryKey: "botol_plastik",
      material: "Botol Plastik PET",
      date: "Kemarin 14:30",
      weightKg: 3.5,
      coins: 35,
      status: "confirmed",
      method: "drop_point",
      dropPointName: "ReBrew Hub Gubeng",
    },
    {
      id: "RB-778",
      categoryKey: "kardus",
      material: "Kardus Kemasan Susu",
      date: "2 hari lalu",
      weightKg: 4.5,
      coins: 54, // dijemput with 20% discount (67.5 -> 54)
      status: "confirmed",
      method: "dijemput",
    },
    {
      id: "RB-777",
      categoryKey: "kaleng",
      material: "Kaleng Susu Evaporasi",
      date: "3 hari lalu",
      weightKg: 1.8,
      coins: 36,
      status: "confirmed",
      method: "drop_point",
      dropPointName: "ReBrew Hub Gubeng",
    },
    {
      id: "RB-776",
      categoryKey: "cup_plastik",
      material: "Cup Plastik PP",
      date: "5 hari lalu",
      weightKg: 1.2,
      coins: 6,
      status: "confirmed",
      method: "drop_point",
      dropPointName: "ReBrew Hub Gubeng",
    },
  ],
  wasteComposition: [
    {
      key: "cup_plastik",
      name: "Cup Plastik",
      weightKg: 5.6,
      percentage: 38,
      points: 28,
      color: "#0284c7",
      icon: "local_cafe",
    },
    {
      key: "kardus",
      name: "Kardus",
      weightKg: 4.5,
      percentage: 31,
      points: 54,
      color: "#d97706",
      icon: "package_2",
    },
    {
      key: "botol_plastik",
      name: "Botol Plastik",
      weightKg: 3.5,
      percentage: 24,
      points: 35,
      color: "#2e7d32",
      icon: "water_bottle",
    },
    {
      key: "kaleng",
      name: "Kaleng",
      weightKg: 1.8,
      percentage: 12,
      points: 36,
      color: "#059669",
      icon: "inventory_2",
    },
    {
      key: "tutup_cup",
      name: "Tutup Cup",
      weightKg: 1.2,
      percentage: 8,
      points: 4,
      color: "#8b5cf6",
      icon: "radio_button_checked",
    },
  ],
  leaderboard: [
    {
      id: "lead-01",
      rank: 1,
      cafeName: "Titik Temu Coffee",
      city: "Surabaya",
      totalKg: 32.4,
      totalPoints: 340,
      tierLabel: "1 Ton Club ⭐⭐",
      avatarInitial: "T",
    },
    {
      id: "lead-02",
      rank: 2,
      cafeName: "Kopi Selamat Cafe",
      city: "Surabaya",
      totalKg: 14.6,
      totalPoints: 148,
      tierLabel: "Eco Partner ⭐",
      isCurrentCafe: true,
      avatarInitial: "K",
    },
    {
      id: "lead-03",
      rank: 3,
      cafeName: "Ruang Seduh Roastery",
      city: "Surabaya",
      totalKg: 12.8,
      totalPoints: 130,
      tierLabel: "Eco Partner ⭐",
      avatarInitial: "R",
    },
    {
      id: "lead-04",
      rank: 4,
      cafeName: "Kopi Kenangan Gubeng",
      city: "Surabaya",
      totalKg: 9.5,
      totalPoints: 95,
      tierLabel: "Starter",
      avatarInitial: "K",
    },
    {
      id: "lead-05",
      rank: 5,
      cafeName: "Daily Dose Coffee",
      city: "Surabaya",
      totalKg: 7.2,
      totalPoints: 72,
      tierLabel: "Starter",
      avatarInitial: "D",
    },
  ],
  dailyMissions: [
    {
      id: "ms-01",
      title: "Pilah 50 Cup Plastik Takeaway",
      description: "Kumpulkan & bersihkan minimal 1.5 kg cup plastik bekas takeaway es kopi.",
      progressKg: 1.5,
      targetKg: 1.5,
      rewardCoins: 25,
      completed: true,
      categoryKey: "cup_plastik",
    },
    {
      id: "ms-02",
      title: "Setor Kardus Kemasan Susu",
      description: "Lipat rapi dan timbang minimal 3 kg kardus stok bahan baku.",
      progressKg: 4.5,
      targetKg: 3.0,
      rewardCoins: 30,
      completed: true,
      categoryKey: "kardus",
    },
    {
      id: "ms-03",
      title: "Pilah Tutup Cup & Lid Injection",
      description: "Pisahkan tutup cup dari gelas sebelum ditimbang minimal 2 kg.",
      progressKg: 1.2,
      targetKg: 2.0,
      rewardCoins: 20,
      completed: false,
      categoryKey: "tutup_cup",
    },
  ],
  badges: [
    {
      id: "bdg-01",
      name: "Pioneer Eco Partner",
      description: "Bergabung dalam gerakan ReBrew micro-hub sejak bulan pertama.",
      icon: "verified",
      unlocked: true,
      unlockedAt: "1 Agu 2026",
      rarity: "rare",
    },
    {
      id: "bdg-02",
      name: "Cup Crusher 100+",
      description: "Telah mendaur ulang lebih dari 100 cup plastik minuman.",
      icon: "local_cafe",
      unlocked: true,
      unlockedAt: "12 Agu 2026",
      rarity: "common",
    },
    {
      id: "bdg-03",
      name: "Zero Waste Hero",
      description: "Mencapai target pengurangan emisi karbon 10 kg CO2 eq.",
      icon: "eco",
      unlocked: false,
      rarity: "epic",
    },
    {
      id: "bdg-04",
      name: "1 Ton Club Member",
      description: "Mengumpulkan total akumulasi 1.000 kg sampah terdaur ulang.",
      icon: "military_tech",
      unlocked: false,
      rarity: "legendary",
    },
  ],
};
